// components-angular/src/components/radio-button.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { AngularWidget } from './core';

let redUI = require('@red-ui/components-core'),
    definition = redUI.RadioButtonDefinition;

@Component({
  selector: 'red-ui-radio-button',
  template: `
    <div style="border: solid 1px blue">
      <red-ui-button 
        *ngFor="let button of buttons; let i = index" 
        [text]="button + (i === _state.selectedIndex ? ' Selected' : '')" 
        (onClick)="_dispatch('buttonClick', i)">
      </red-ui-button>
    </div>
  `,
})
export class RadioButton extends AngularWidget {
  @Input()
  selectedIndex = 0;

  @Output()
  onSelectedIndexChanged = new EventEmitter();

  constructor() {
    super(definition);
  }
}

// components-react/src/components/radio-button.jsx
import React from 'react';
import { RadioButtonDefinition, dispatch } from '@red-ui/components-core';
import { ReactWidget } from './core';
import { ButtonPure, Button } from './button';

export class RadioButton extends ReactWidget {
    constructor(props) {
        super(props, RadioButtonDefinition)
        this.onButtonClickHandler = this.onButtonClickHandler.bind(this);
    }
    onButtonClickHandler(i, nativeArgs) {
        this._dispatch('buttonClick', i, nativeArgs);
    }
    render() {
        return <div style={{ border: 'solid 1px blue' }}>
        {this.props.buttons.map((button, i) => {
            return <Button key={i} text={button + (i === this.state.selectedIndex ? ' Selected' : '')} onClick={(args) => this.onButtonClickHandler(i, args)}></Button>
        })}
    </div>

    }
}

RadioButton.defaultProps = RadioButtonDefinition.defaultProps;
